#!/usr/bin/env bash
#
# Initialize the Freva Redis instance with TLS and ACL support.
set  -o nounset -o pipefail -o errexit
[ "${DEBUG:-}" = "true" ] && set -x
export SERVICE=redis


TMP_DIR=$(mktemp -d --suffix=_redis -q)
REDIS_CONFIG="$TMP_DIR/redis.conf"
CONFIG="$CONFIG_DIR/data-portal-cluster-config.json"
JSON="{}"

trap 'rm -rf "$TMP_DIR"' EXIT INT TERM

if [ "${OVERRIDE:-0}" = "1" ];then
    rm -r $CONFIG
fi

if ([ "${CONFIG_CONTENT:-}" ] && [ ! -f "$CONFIG" ]);then
    mkdir -p $CONFIG_DIR
    echo "$CONFIG_CONTENT" > $CONFIG
fi
if [ -f "$CONFIG" ]; then
    JSON=$(base64 --decode < "$CONFIG")
fi

parse_json_value() {
  local key=$1
  echo "$JSON" | jq -r ".${1} // \"\""
}

REDIS_USER=${REDIS_USERNAME:-$(parse_json_value user)}
REDIS_PASSWORD=${REDIS_PASSWORD:-$(parse_json_value passwd)}
REDIS_CERT=$(parse_json_value ssl_cert)
REDIS_KEY=$(parse_json_value ssl_key)

REDIS_PASSWORD="${REDIS_PASSWORD:+>$REDIS_PASSWORD}"
REDIS_USER="${REDIS_USER:+$REDIS_USER}"
REDIS_SSL_CERTFILE="${REDIS_SSL_CERTFILE:-$TMP_DIR/redis-ca-cert.crt}"
REDIS_SSL_KEYFILE="${REDIS_SSL_KEYFILE:-$TMP_DIR/redis-key.key}"

# Configure Redis user ACL
if [ -n "$REDIS_USER" ]; then
    echo "user default off -@all" >> "$REDIS_CONFIG"
fi



echo "user ${REDIS_USER:-default} on +@all ~* &* ${REDIS_PASSWORD:-nopass}" >> "$REDIS_CONFIG"

# Logging config
echo "loglevel ${REDIS_LOGLEVEL:-notice}" >> "$REDIS_CONFIG"
echo "syslog-enabled yes" >> "$REDIS_CONFIG"
# TLS setup
if [ -n "$REDIS_CERT" ] && [ -n "$REDIS_KEY" ]; then
    echo "$REDIS_CERT" > "$REDIS_SSL_CERTFILE"
    echo "$REDIS_KEY" > "$REDIS_SSL_KEYFILE"
    chmod 0600 "$REDIS_SSL_CERTFILE" "$REDIS_SSL_KEYFILE"
fi

if [ -f "$REDIS_SSL_CERTFILE" ] && [ -f "$REDIS_SSL_KEYFILE" ];then
    cat >> "$REDIS_CONFIG" <<EOF
port 0
tls-port ${REDIS_PORT:-6379}
tls-cert-file $REDIS_SSL_CERTFILE
tls-key-file $REDIS_SSL_KEYFILE
tls-ca-cert-file $REDIS_SSL_CERTFILE
tls-protocols TLSv1.3
EOF
else
    echo port ${REDIS_PORT:-6379} >> ${REDIS_CONFIG}
fi

# Directories and final config
echo "dir $DATA_DIR" >> "$REDIS_CONFIG"
echo "logfile $LOG_DIR/redis-${REDIS_PORT:-6379}.log" >> "$REDIS_CONFIG"
echo "pidfile /tmp/redis-server-${REDIS_PORT:-6379}.pid" >> "$REDIS_CONFIG"
echo "Created Redis with config:"
echo -e "################### START: $(date) ###################\n" >  $LOG_DIR/redis-${REDIS_PORT:-6379}.log
cat "$REDIS_CONFIG" >> $LOG_DIR/redis-${REDIS_PORT:-6379}.log
echo "" $LOG_DIR/redis-${REDIS_PORT:-6379}.log
exec redis-server "$REDIS_CONFIG"
