name: Build and Push Freva Service Images

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [mongo, mysql, redis, solr]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Extract version from image
        id: version
        run: |
          VERSION=$(bash version-inspect.sh ${{ matrix.service }} | tr -d '\r\n')
          echo "Detected version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set push flag
        id: push
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service }}
          file: ${{ matrix.service }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          build-args: VERSION=${{ steps.version.outputs.version }}
          # push: ${{ steps.push.outputs.push }}
          push: true
          no-cache: true
          tags: |
            ghcr.io/freva-clint/freva-${{ matrix.service }}:latest
            ghcr.io/freva-clint/freva-${{ matrix.service }}:${{ steps.version.outputs.version }}
